### ISSUE TITLE
Could not pass inventorycreativeevent

### ISSUE THREAD

**Issue by JohnnyS** [trentech/EasyKits-for-Bukkit#1]
```
[18:56:50` ERROR]: Could not pass event InventoryCreativeEvent to EasyKits v2.0.3
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getTitle()'
at info.TrenTech.EasyKits.Events.MainListener.onPlayerClickKitEvent(MainListener.java:61) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor403.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-205]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-205]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-205]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2489) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-205]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-205]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

This is the error I am getting in my console can someone help?

**Comment by trentech** [comment]
This is an old unsupported version. Update to the Beta release that was uploaded yesterday

**Comment by JohnnyS** [comment]
So I did put it but it still shows as 2.0.3. Do I have to delete the old folder ?
