### ISSUE TITLE
An Internal Error Occurred 

### ISSUE THREAD

**Issue by daytonh27** [trentech/EasyKits-for-Bukkit#11]
Hey, The plugin works perfectly after I install it, but whenever the server reloads or restarts I can no longer use any easy kit commands. I only get these errors in game:

An Internal Error has Occurred While trying to Tab-complete this command
An internal Error has Occurred while trying to perform this command

This is the console error:

[00:42:13] [Server thread/INFO]: Zifa issued server command: /kit peasant
[00:42:13] [Server thread/WARN]: org.trentech.easykits.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90020 not found) [90020-200]
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.message.DbException.getJdbcSQLException(DbException.java:622)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.message.DbException.get(DbException.java:194)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:206)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Database.getPageStore(Database.java:2659)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Database.open(Database.java:675)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Database.openDatabase(Database.java:307)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Database.<init>(Database.java:301)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Engine.openSession(Engine.java:74)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Engine.openSession(Engine.java:192)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Engine.createSession(Engine.java:166)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.Engine.createSession(Engine.java:29)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.Driver.connect(Driver.java:69)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.sql.SQLUtils.getConnection(SQLUtils.java:17)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.sql.SQLKits.get(SQLKits.java:82)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.kits.KitService.getKit(KitService.java:29)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.commands.CMDKit.execute(CMDKit.java:29)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.commands.CommandHandler.onCommand(CommandHandler.java:40)
[00:42:13] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:42:13] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[00:42:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1933)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1776)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1729)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1051)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1044)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1028)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:960)
[00:42:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[00:42:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:42:13] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/minecraft/multicraft/servers/server631744/plugins/EasyKits/data.db.mv.db [1.4.200/7]
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.FileStore.open(FileStore.java:166)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.MVStore.<init>(MVStore.java:381)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
[00:42:13] [Server thread/WARN]: 	... 39 more
[00:42:13] [Server thread/WARN]: Caused by: java.nio.channels.OverlappingFileLockException
[00:42:13] [Server thread/WARN]: 	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
[00:42:13] [Server thread/WARN]: 	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
[00:42:13] [Server thread/WARN]: 	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
[00:42:13] [Server thread/WARN]: 	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
[00:42:13] [Server thread/WARN]: 	at org.trentech.easykits.h2.mvstore.FileStore.open(FileStore.java:163)
[00:42:13] [Server thread/WARN]: 	... 42 more
[00:42:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'kit' in plugin EasyKits v2.3.7

**Comment by trentech** [comment]
You have something locking the data file as indicated here:

[00:42:13] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/minecraft/multicraft/servers/server631744/plugins/EasyKits/data.db.mv.db [1.4.200/7]

I've been unable to replicate this issue with the latest version. This shouldn't occur if the server is properly restarted as there would be nothing server side locking the file. This could be caused by outside sources like a backup application or remote monitoring maybe.

Please try the latest version and see if the problem persists
https://github.com/trentech/EasyKits-for-Bukkit/releases/tag/v2.3.8
