### ISSUE TITLE
Could not pass event InventoryClickEvent to EasyKits v.2.0.3 Error Please help

### ISSUE THREAD

**Issue by Tuinierder** [trentech/EasyKits-for-Bukkit#3]
Hello i have a problem in the console what i cant fix, its spamming my console full so i cant see anything else... 
Here is the error:
[11:30:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EasyKits v2.0.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$3057.000000009007EE90.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:819) [?:1.8.0_232]
Caused by: java.lang.NoSuchMethodError: org/bukkit/inventory/Inventory.getTitle()Ljava/lang/String; (loaded from file:/home/container/server.jar by sun.misc.Launcher$AppClassLoader@a68a15bd) called from class info.TrenTech.EasyKits.Events.MainListener (loaded from file:/home/container/plugins/EasyKits-v2.0.5.jar by org.bukkit.plugin.java.PluginClassLoader@bef13fb6).
at info.TrenTech.EasyKits.Events.MainListener.onPlayerClickKitEvent(MainListener.java:61) ~[?:?]
at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-800b93f-8160e29]
... 18 more

**Comment by tiarnia** [comment]
yeah mine does that on the 1.9 version and it slows things down but at least it works the new version won't work for me at all

**Comment by Tuinierder** [comment]
Looks like it was nothing with the plugin, I deleted the plugin and installed another one. Same error.
I'll tell you how to fix it: there is an enum wrong (it's and effect that's plymayed when something happens). https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
This list will show you all the valid enums there are (this one is for 1.15.2) if you replace the effect with one of those you'll probably not receive any errors on the console.

**Comment by trentech** [comment]
This is an old issue that was alread y resolved in beta versions
